"""Environment variables injected into scheduler-managed processor containers."""

from __future__ import annotations

import os
from typing import Any


def processor_infra_env() -> dict[str, str]:
    """Pass through connectivity settings so processors reach infra from Docker networks."""
    mapping: dict[str, str] = {}
    passthrough = (
        "DOCUMENT_JOBS_MYSQL_HOST",
        "DOCUMENT_JOBS_MYSQL_PORT",
        "DOCUMENT_JOBS_MYSQL_USER",
        "DOCUMENT_JOBS_MYSQL_PASSWORD",
        "DOCUMENT_JOBS_MYSQL_DATABASE",
        "DOCUMENT_JOBS_POSTGRES_HOST",
        "DOCUMENT_JOBS_POSTGRES_PORT",
        "DOCUMENT_JOBS_POSTGRES_USER",
        "DOCUMENT_JOBS_POSTGRES_PASSWORD",
        "DOCUMENT_JOBS_POSTGRES_DATABASE",
        "OBSERVABILITY_POSTGRES_HOST",
        "OBSERVABILITY_POSTGRES_PORT",
        "OBSERVABILITY_POSTGRES_USER",
        "OBSERVABILITY_POSTGRES_PASSWORD",
        "OBSERVABILITY_POSTGRES_DB",
        "POSTGRES_HOST",
        "POSTGRES_PORT",
        "POSTGRES_USER",
        "POSTGRES_PASSWORD",
        "POSTGRES_DB",
        "WEAVIATE_URL",
        "WEAVIATE_API_KEY",
        "WEAVIATE_GRPC_PORT",
        "WEAVIATE_COLLECTION",
        "NEO4J_URI",
        "NEO4J_USER",
        "NEO4J_PASSWORD",
        "REDIS_HOST",
        "REDIS_PORT",
        "REDIS_PASSWORD",
        "RABBITMQ_HOST",
        "RABBITMQ_PORT",
        "RABBITMQ_USER",
        "RABBITMQ_PASS",
        "RABBITMQ_QUEUE_NAME",
        "EMBEDDING_MODEL",
        "MODEL_NAME",
        "MODEL_DIR",
        "DOCUMENT_CLASSIFIER_PRELOAD",
        "HF_HUB_OFFLINE",
        "TRANSFORMERS_OFFLINE",
        "RENDER_CACHE_TTL_SECONDS",
        # Upload security always runs in processor; LITE skips heavy optional models.
        "SECURITY_PIPELINE_LITE",
        "SECURITY_POLICY_DIR",
        "PROCESSORS_CONFIG_PATH",
        "SECURITY_AUDIT_LOG_PATH",
        "CONFIDENTIAL_CORPUS_DIR",
        "LLM_MODERATION_PROVIDER",
        "OPENAI_API_KEY",
        "CIH_OPENAI_API_KEY",
        "CIH_TRANSCRIPTION_PROVIDER",
        "CIH_WHISPER_MODEL",
        "CIH_WHISPER_DEPLOYMENT",
        "CIH_WHISPER_API_VERSION",
        "CIH_FASTER_WHISPER_MODEL",
        "CIH_LOCAL_WHISPER_MODEL",
        "CIH_LOCAL_WHISPER_DEVICE",
        "CIH_LOCAL_WHISPER_COMPUTE",
        "ASR_PROVIDER",
        "ASR_MODEL_NAME",
        "ASR_FALLBACK_MODEL_NAME",
        "ASR_COMPUTE_TYPE",
        "ASR_LANGUAGE",
        "ASR_TASK",
        "ASR_BEAM_SIZE",
        "ASR_BEST_OF",
        "CIH_TRANSCRIPT_TO_ENGLISH",
        "ASR_TRANSLATE_TO_ENGLISH",
        "CIH_FORCE_RETRANSCRIBE",
        "OPEN_WEIGHT_VLM_ENABLED",
        "OPEN_WEIGHT_VLM_API_URL",
        "OPEN_WEIGHT_VLM_API_KEY",
        "OPEN_WEIGHT_VLM_MODEL",
        "OPEN_WEIGHT_VLM_TIMEOUT_SECONDS",
        "OPEN_WEIGHT_VLM_CONFIDENCE",
        "OLLAMA_HOST",
        "OLLAMA_API_KEY",
        "OLLAMA_TRANSLATION_MODEL",
        "CIH_IMAGE_SUMMARY_PROVIDER",
        "GEMINI_API_KEY",
        "GEMINI_MODEL_NAME",
        "IMAGE_DESCRIPTION_ENABLED",
        "AZURE_OPENAI_API_KEY",
        "AZURE_OPENAI_ENDPOINT",
        "AZURE_OPENAI_API_VERSION",
        "AZURE_OPENAI_WHISPER_DEPLOYMENT",
        "LLAMA_GUARD_URL",
        "CONTENT_INTELLIGENCE_USE_TEMPLATE",
        "CONTENT_INTELLIGENCE_ENRICH_SOP",
        "CONTENT_INTELLIGENCE_PERSIST_NEO4J",
        "CONTENT_INTELLIGENCE_RISK_KEYWORDS",
        "CONTENT_INTELLIGENCE_RISK_WEIGHT",
        "CONTENT_INTELLIGENCE_RISK_THRESHOLD",
    )
    for key in passthrough:
        value = os.getenv(key)
        if value is not None and str(value).strip() != "":
            mapping[key] = str(value).strip()
    return mapping
